"""
This script infers a height distribution from the point map generated by VGGT.
"""

import numpy as np
import argparse
import open3d as o3d
import matplotlib.pyplot as plt
from pathlib import Path

def parse_args():
    parser = argparse.ArgumentParser(
        description="Infer height distribution from point map"
    )
    parser.add_argument(
        "--pointmap_path",
        type=str,
        required=True,
        help="Path to the input point map file (e.g., .npy or .ply)",
    )
    parser.add_argument(
        "--top_view_axis",
        type=str,
        default="z",
        choices=["x", "y", "z"],
        help="To decide which view is the top-down view (default: z axis as height)",
    )

    parser.add_argument("--resolution", type=int, default=300, help="Number of 'bins' along each axis")
    
    return parser.parse_args()

def conversion_factor():
    """
    Calculates the conversion factor from VGGT point cloud to physical units. 
    Use the ratio between known depth to VGGT predicted depth over a range of reference points.
    """
    # Placeholder implementation
    return 1.0

def plot_height_distribution(top_view_axis, h_max_x, h_min_x, h_max_y, h_min_y, x_bins, y_bins, save_fig=False, output_dir=None):
    """
    Plots (1) 2D heatmap of height distribution, (2) 3D scatter of height over (x, y).
    
    Args:
        h_max_x: max height per x bin (resolution,)
        h_min_x: min height per x bin (resolution,)
        h_max_y: max height per y bin (resolution,)
        h_min_y: min height per y bin (resolution,)
        x_bins: bin edges for x axis (resolution+1,)
        y_bins: bin edges for y axis (resolution+1,)
        output_dir: directory to save plots (optional)
    """
    resolution = len(h_max_x)
    
    # Compute bin centers
    x_centers = (x_bins[:-1] + x_bins[1:]) / 2
    y_centers = (y_bins[:-1] + y_bins[1:]) / 2
    
    # Compute height grid: h(x, y) = min(h_max_x[x], h_max_y[y]) - max(h_min_x[x], h_min_y[y])
    height_grid = np.zeros((resolution, resolution))
    for i in range(resolution):
        for j in range(resolution):
            if np.isfinite(h_max_x[i]) and np.isfinite(h_max_y[j]) and \
               np.isfinite(h_min_x[i]) and np.isfinite(h_min_y[j]):
                h_top = min(h_max_x[i], h_max_y[j])
                h_bottom = max(h_min_x[i], h_min_y[j])
                height_grid[i, j] = max(0, h_top - h_bottom)
            else:
                height_grid[i, j] = np.nan

    # 1) 2D Heatmap of height distribution
    plt.figure(figsize=(8, 6))
    valid_heights = height_grid[np.isfinite(height_grid) & (height_grid > 0)]
    if len(valid_heights) > 0:
        plt.imshow(height_grid.T, origin='lower', aspect='auto', cmap='viridis',
                   extent=[x_bins[0], x_bins[-1], y_bins[0], y_bins[-1]])
        plt.colorbar(label='Height')
        plt.xlabel('X Coordinate')
        plt.ylabel('Y Coordinate')
        plt.title('Height Distribution Heatmap')
        plt.grid(alpha=0.3)
        
        # Make axes equal scale
        ax = plt.gca()
        ax.set_aspect('equal', adjustable='box')
    
    plt.tight_layout()
    if save_fig: 
        plt.savefig(f"{output_dir}/height_heatmap_{top_view_axis}.png", dpi=200)
        print(f"Saved height heatmap to {output_dir}/height_heatmap_{top_view_axis}.png")
    else:
        plt.show()
    plt.close()

    # 2) 3D Scatter plot of h_max and h_min over (x, y)
    fig = plt.figure(figsize=(10, 8))
    ax = fig.add_subplot(111, projection='3d')
    
    # Create meshgrid for valid points
    x_coords = []
    y_coords = []
    h_top_list = []
    h_bottom_list = []
    
    for i in range(resolution):
        for j in range(resolution):
            if np.isfinite(h_max_x[i]) and np.isfinite(h_max_y[j]) and \
               np.isfinite(h_min_x[i]) and np.isfinite(h_min_y[j]):
                h_top = min(h_max_x[i], h_max_y[j])
                h_bottom = max(h_min_x[i], h_min_y[j])
                if h_top > h_bottom:
                    x_coords.append(x_centers[i])
                    y_coords.append(y_centers[j])
                    h_top_list.append(h_top)
                    h_bottom_list.append(h_bottom)
    
    x_arr = np.array(x_coords)
    y_arr = np.array(y_coords)
    h_top_arr = np.array(h_top_list)
    h_bottom_arr = np.array(h_bottom_list)
    
    if len(x_arr) > 0:
        # Plot top surface (h_max)
        s1 = ax.scatter(x_arr, y_arr, h_top_arr, c=h_top_arr, cmap='viridis', s=6, label='h_max')
        # Plot bottom surface (h_min)
        s2 = ax.scatter(x_arr, y_arr, h_bottom_arr, c=h_bottom_arr, cmap='plasma', s=6, label='h_min', alpha=0.6)
        
        ax.set_xlabel('X Coordinate')
        ax.set_ylabel('Y Coordinate')
        ax.set_zlabel('Height')
        ax.set_title('3D Scatter: Height Over Footprint')
        ax.view_init(elev=35, azim=-60)
        ax.legend(loc='upper right')
        fig.colorbar(s1, ax=ax, shrink=0.6, label='Height')
        
        # Make X and Y same scale
        x_span = max(x_arr.max() - x_arr.min(), 1e-9)
        y_span = max(y_arr.max() - y_arr.min(), 1e-9)
        h_span = max(h_top_arr.max() - h_bottom_arr.min(), 1e-9)
        ax.set_box_aspect((x_span, y_span, h_span))
    
    plt.tight_layout()
    if output_dir:
        plt.savefig(f"{output_dir}/height_3d_scatter_{top_view_axis}.png", dpi=300)
        print(f"Saved 3D scatter to {output_dir}/height_3d_scatter_{top_view_axis}.png")
    else:
        plt.show()
    plt.close(fig)

    # (3) Plot the two 1D height profiles along x and y axes
    plt.figure(figsize=(10, 4))
    plt.subplot(1, 2, 1)
    plt.plot(x_centers, h_max_x, label='h_max_x', color='blue')
    plt.plot(x_centers, h_min_x, label='h_min_x', color='cyan')
    plt.xlabel('X Coordinate')
    plt.ylabel('Height')
    plt.title('Height Profile along X-axis')
    plt.legend()
    plt.grid(alpha=0.3)

    plt.subplot(1, 2, 2)
    plt.plot(y_centers, h_max_y, label='h_max_y', color='blue')
    plt.plot(y_centers, h_min_y, label='h_min_y', color='cyan')
    plt.xlabel('Y Coordinate')
    plt.ylabel('Height')
    plt.title('Height Profile along Y-axis')
    plt.legend()
    plt.grid(alpha=0.3)

    plt.tight_layout()
    if save_fig:
        plt.savefig(f"{output_dir}/height_profiles_{top_view_axis}.png", dpi=200)
        print(f"Saved height profiles to {output_dir}/height_profiles_{top_view_axis}.png")
    else:
        plt.show()
    plt.close()


def infer_height_distribution(top_view_axis, pointmap_path, resolution=300):
    """
    Infers the height distribution from the given point map file.
    """
    point_map = o3d.io.read_point_cloud(pointmap_path)
    points = np.asarray(point_map.points) # (N, 3)
    print("Number of points loaded:", points.shape[0])

    # Rotate the point clouds if viewing axis is not z
    if top_view_axis == "z":
        pass
    elif top_view_axis == "y":
        # Swap y and z
        points = points[:, [0, 2, 1]]
    elif top_view_axis == "x":
        # Swap x and z
        points = points[:, [2, 1, 0]]


    # Identify the range of x, y, z coordinates
    x_min, y_min, z_min = points.min(axis=0)
    x_max, y_max, z_max = points.max(axis=0)

    # Traverse all points and find the h_max and h_min for each x bin and y bin

    x_bins = np.linspace(x_min, x_max, resolution + 1)
    y_bins = np.linspace(y_min, y_max, resolution + 1)

    h_max_x = np.full((resolution), -np.inf) # h_max(x)
    h_min_x = np.full((resolution), np.inf) # h_min(x)
    h_max_y = np.full((resolution), -np.inf) # h_max(y)
    h_min_y = np.full((resolution), np.inf) # h_min(y)

    for point in points:
        x, y, z = point
        # Find the bin index for x and y
        x_idx = np.searchsorted(x_bins, x) - 1
        y_idx = np.searchsorted(y_bins, y) - 1

        if 0 <= x_idx < resolution and 0 <= y_idx < resolution:
            h_max_x[x_idx] = max(h_max_x[x_idx], z)
            h_min_x[x_idx] = min(h_min_x[x_idx], z)
            h_max_y[y_idx] = max(h_max_y[y_idx], z)
            h_min_y[y_idx] = min(h_min_y[y_idx], z)

    
    # Get the volume by summing over all bins
    pixel_area = ((x_max - x_min) / resolution) * ((y_max - y_min) / resolution) # area of each 2D segment
    volume = 0.0
    for x in range(len(h_min_x)):
        for y in range(len(h_min_y)):

            height = min(h_max_x[x], h_max_y[y]) - max(h_min_x[x], h_min_y[y])
            if height > 0:
                volume += height * pixel_area

    
    # Plot height distribution
    # Get output dir
    output_dir = Path(pointmap_path).parent.parent / "vggt_height_distribution"
    output_dir.mkdir(parents=True, exist_ok=True)
    plot_height_distribution(top_view_axis, h_max_x, h_min_x, h_max_y, h_min_y, x_bins, y_bins, save_fig=True, output_dir=output_dir)

    return h_max_x, h_min_x, h_max_y, h_min_y, volume

def render_side_views(top_view_axis, pointmap_path, output_dir=None):
    """
    Renders side views of the point cloud (from X and Y directions) and saves as images.
    """
    point_map = o3d.io.read_point_cloud(pointmap_path)
    points = np.asarray(point_map.points)
    colors = np.asarray(point_map.colors) if point_map.has_colors() else None

    # Rotate the entire point cloud is top_view_axis is not z
    if top_view_axis == "z":
        pass
    elif top_view_axis == "y":
        # Swap y and z
        points = points[:, [0, 2, 1]]
        if colors is not None:
            colors = colors[:, [0, 2, 1]]
    elif top_view_axis == "x":
        # Swap x and z
        points = points[:, [2, 1, 0]]
        if colors is not None:
            colors = colors[:, [2, 1, 0]]


    if output_dir is None:
        output_dir = Path(pointmap_path).parent.parent / "vggt_height_distribution"
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Get point cloud bounds
    x_min, y_min, z_min = points.min(axis=0)
    x_max, y_max, z_max = points.max(axis=0)
    
    # --- View from X direction (Y-Z plane) ---
    plt.figure(figsize=(10, 8))
    if colors is not None:
        plt.scatter(points[:, 1], points[:, 2], c=colors, s=0.5, alpha=0.5)
    else:
        plt.scatter(points[:, 1], points[:, 2], c=points[:, 0], cmap='viridis', s=0.5, alpha=0.5)
        plt.colorbar(label='X depth')
    plt.xlabel('Y Coordinate')
    plt.ylabel('Z Coordinate (Height)')
    plt.title('Side View from X Direction (Y-Z Plane)')
    plt.axis('equal')
    plt.grid(alpha=0.3)
    plt.tight_layout()
    plt.savefig(output_dir / f"side_view_from_x(top_{top_view_axis}).png", dpi=200)
    print(f"Saved side view from X to {output_dir}/side_view_from_x(top_{top_view_axis}).png")
    plt.close()
    
    # --- View from Y direction (X-Z plane) ---
    plt.figure(figsize=(10, 8))
    if colors is not None:
        plt.scatter(points[:, 0], points[:, 2], c=colors, s=0.5, alpha=0.5)
    else:
        plt.scatter(points[:, 0], points[:, 2], c=points[:, 1], cmap='viridis', s=0.5, alpha=0.5)
        plt.colorbar(label='Y depth')
    plt.xlabel('X Coordinate')
    plt.ylabel('Z Coordinate (Height)')
    plt.title('Side View from Y Direction (X-Z Plane)')
    plt.axis('equal')
    plt.grid(alpha=0.3)
    plt.tight_layout()
    plt.savefig(output_dir / f"side_view_from_y(top_{top_view_axis}).png", dpi=200)
    print(f"Saved side view from Y to {output_dir}/side_view_from_y(top_{top_view_axis}).png")
    plt.close()
    
    # --- Top-down view (X-Y plane) ---
    plt.figure(figsize=(10, 8))
    if colors is not None:
        plt.scatter(points[:, 0], points[:, 1], c=colors, s=0.5, alpha=0.5)
    else:
        plt.scatter(points[:, 0], points[:, 1], c=points[:, 2], cmap='viridis', s=0.5, alpha=0.5)
        plt.colorbar(label='Z (Height)')
    plt.xlabel('X Coordinate')
    plt.ylabel('Y Coordinate')
    plt.title('Top-Down View (X-Y Plane)')
    plt.axis('equal')
    plt.grid(alpha=0.3)
    plt.tight_layout()
    plt.savefig(output_dir / f"top_down_view(top_{top_view_axis}).png", dpi=200)
    print(f"Saved top-down view to {output_dir}/top_down_view(top_{top_view_axis}).png")
    plt.close()
    
    print(f"\nPoint cloud bounds:")
    print(f"  X: [{x_min:.4f}, {x_max:.4f}]")
    print(f"  Y: [{y_min:.4f}, {y_max:.4f}]")
    print(f"  Z: [{z_min:.4f}, {z_max:.4f}]")

def main():
    args = parse_args()

    _, _, _, _, volume = infer_height_distribution(args.top_view_axis, args.pointmap_path, args.resolution)
    print("Inferred Height Distribution:")
    print("Resolution:", args.resolution)
    print("Volume:", volume)

    render_side_views(args.top_view_axis, args.pointmap_path, output_dir=None)

if __name__ == "__main__":
    main()